# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Functions

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Prepare for Tests
      run: "sudo mkdir -p /etc/elements/repos; sudo curl -Lo /usr/bin/pacman https://github.com/icy/pacapt/raw/ng/pacapt; sudo chmod 755 /usr/bin/pacman; sudo apt update"
    - name: Installing elements-search modules
      run: "git clone https://github.com/tekq/elements-search.git; sudo mv -vf elements-search/search-repo /etc/elements/; sudo mv -vf elements-search/search /etc/elements/; sudo chmod +x /etc/elements/{search,search-repo}; sudo rm -rvf elements-search"
    - name: Testing installing
      run: "sudo python lmt.py install neofetch"
    - name: Testing removing
      run: "sudo python lmt.py remove neofetch"
    - name: Testing updating
      run: "sudo python lmt.py update"
    - name: Testing repo ref
      run: "sudo python lmt.py refresh"
      
